Fix various problems listed in [Bug 1881216]

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -309,7 +309,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS CYGPATH EXEEXT PKG_LIB_FILE PKG_STUB_LIB_FILE PKG_STUB_SOURCES PKG_STUB_OBJECTS PKG_TCL_SOURCES PKG_HEADERS PKG_INCLUDES PKG_LIBS PKG_CFLAGS TCL_VERSION TCL_BIN_DIR TCL_SRC_DIR TCL_LIB_FILE TCL_LIB_FLAG TCL_LIB_SPEC TCL_STUB_LIB_FILE TCL_STUB_LIB_FLAG TCL_STUB_LIB_SPEC TCL_LIBS TCL_DEFS TCL_EXTRA_CFLAGS TCL_LD_FLAGS TCL_SHLIB_LD_LIBS CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC OBJEXT CPP INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA SET_MAKE RANLIB ac_ct_RANLIB EGREP MATH_LIBS PKG_SOURCES PKG_OBJECTS RC RES_SUFFIX RES_DEFS PKG_PRIVATE_HEADERS TCL_TOP_DIR_NATIVE TCL_GENERIC_DIR_NATIVE TCL_UNIX_DIR_NATIVE TCL_WIN_DIR_NATIVE TCL_BMAP_DIR_NATIVE TCL_TOOL_DIR_NATIVE TCL_PLATFORM_DIR_NATIVE TCL_INCLUDES TCL_THREADS SHARED_BUILD AR CELIB_DIR LIBOBJS DL_LIBS CFLAGS_DEBUG CFLAGS_OPTIMIZE CFLAGS_WARNING STLIB_LD SHLIB_LD SHLIB_LD_LIBS SHLIB_CFLAGS LD_LIBRARY_PATH_VAR CFLAGS_DEFAULT LDFLAGS_DEFAULT TCL_DBGX MAKE_LIB MAKE_SHARED_LIB MAKE_STATIC_LIB MAKE_STUB_LIB RANLIB_STUB MT ADD_MANIFEST CLEANFILES TCLSH_PROG CONFIGURE_OUTPUTS SDX SDX_KIT TCLOO_INCLUDE_SPEC TCLOO_PRIVATE_INCLUDE_SPEC TCLOO_LIB_SPEC TCLOO_STUB_LIB_SPEC LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS CYGPATH EXEEXT PKG_LIB_FILE PKG_STUB_LIB_FILE PKG_STUB_SOURCES PKG_STUB_OBJECTS PKG_TCL_SOURCES PKG_HEADERS PKG_INCLUDES PKG_LIBS PKG_CFLAGS TCL_VERSION TCL_BIN_DIR TCL_SRC_DIR TCL_LIB_FILE TCL_LIB_FLAG TCL_LIB_SPEC TCL_STUB_LIB_FILE TCL_STUB_LIB_FLAG TCL_STUB_LIB_SPEC TCL_LIBS TCL_DEFS TCL_EXTRA_CFLAGS TCL_LD_FLAGS TCL_SHLIB_LD_LIBS CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC OBJEXT CPP INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA SET_MAKE RANLIB ac_ct_RANLIB EGREP MATH_LIBS PKG_SOURCES PKG_OBJECTS PKG_PRIVATE_HEADERS TCL_TOP_DIR_NATIVE TCL_GENERIC_DIR_NATIVE TCL_UNIX_DIR_NATIVE TCL_WIN_DIR_NATIVE TCL_BMAP_DIR_NATIVE TCL_TOOL_DIR_NATIVE TCL_PLATFORM_DIR_NATIVE TCL_INCLUDES TCL_THREADS SHARED_BUILD AR CELIB_DIR LIBOBJS DL_LIBS CFLAGS_DEBUG CFLAGS_OPTIMIZE CFLAGS_WARNING STLIB_LD SHLIB_LD SHLIB_LD_LIBS SHLIB_CFLAGS LD_LIBRARY_PATH_VAR RC RES_SUFFIX RES_DEFS CFLAGS_DEFAULT LDFLAGS_DEFAULT TCL_DBGX MAKE_LIB MAKE_SHARED_LIB MAKE_STATIC_LIB MAKE_STUB_LIB RANLIB_STUB CC_OUT MT ADD_MANIFEST CLEANFILES TCLSH_PROG CONFIGURE_OUTPUTS SDX SDX_KIT TCLOO_INCLUDE_SPEC TCLOO_PRIVATE_INCLUDE_SPEC TCLOO_LIB_SPEC TCLOO_STUB_LIB_SPEC LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -6197,81 +6197,6 @@ echo "$as_me: error: could not find source file '$i'" >&2;}
 
 
 
-    dirs=""${srcdir}/generic""
-    vars="PACKAGE_NAME PKG_LIB_FILE PACKAGE_VERSION"
-    if test ${TEA_PLATFORM} = "windows"; then
-
-	for ac_prog in windres rc
-do
-  # Extract the first word of "$ac_prog", so it can be a program name with args.
-set dummy $ac_prog; ac_word=$2
-echo "$as_me:$LINENO: checking for $ac_word" >&5
-echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
-if test "${ac_cv_prog_RC+set}" = set; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-  if test -n "$RC"; then
-  ac_cv_prog_RC="$RC" # Let the user override the test.
-else
-as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
-for as_dir in $PATH
-do
-  IFS=$as_save_IFS
-  test -z "$as_dir" && as_dir=.
-  for ac_exec_ext in '' $ac_executable_extensions; do
-  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
-    ac_cv_prog_RC="$ac_prog"
-    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
-    break 2
-  fi
-done
-done
-
-fi
-fi
-RC=$ac_cv_prog_RC
-if test -n "$RC"; then
-  echo "$as_me:$LINENO: result: $RC" >&5
-echo "${ECHO_T}$RC" >&6
-else
-  echo "$as_me:$LINENO: result: no" >&5
-echo "${ECHO_T}no" >&6
-fi
-
-  test -n "$RC" && break
-done
-test -n "$RC" || RC="none"
-
-	case $RC in
-	    windres)
-		rcdef_inc="--include "
-		rcdef_start="--define "
-		rcdef_q='\"'
-		RES_SUFFIX=res.o
-
-		PKG_OBJECTS="${PKG_OBJECTS} ${PACKAGE_NAME}.res.o" ;;
-	    rc)
-		rcdef_inc="/i "
-		rcdef_start="/d "
-		rcdef_q='"'
-		RES_SUFFIX=res
-
-		PKG_OBJECTS="${PKG_OBJECTS} ${PACKAGE_NAME}.res" ;;
-	    none)
-		{ echo "$as_me:$LINENO: WARNING: could not find resource compiler" >&5
-echo "$as_me: WARNING: could not find resource compiler" >&2;}
-		RC=: ;;
-	esac
-fi
-
-    for i in $dirs; do
-	RES_DEFS="${RES_DEFS} ${rcdef_inc}\"`${CYGPATH} $i`\""
-    done
-    for i in $vars; do
-	RES_DEFS="$RES_DEFS ${rcdef_start}$i='${rcdef_q}\$($i)${rcdef_q}'"
-    done
-
-
     vars="tclOOStubLib.c"
     for i in $vars; do
 	# check for existence - allows for generic/win/unix VPATH
@@ -10109,6 +10034,81 @@ echo "${ECHO_T}no" >&6
 
 
 
+    dirs=""${srcdir}/generic""
+    vars="PACKAGE_NAME PKG_LIB_FILE PACKAGE_VERSION"
+    if test ${TEA_PLATFORM} = "windows"; then
+
+	for ac_prog in windres rc
+do
+  # Extract the first word of "$ac_prog", so it can be a program name with args.
+set dummy $ac_prog; ac_word=$2
+echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_prog_RC+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  if test -n "$RC"; then
+  ac_cv_prog_RC="$RC" # Let the user override the test.
+else
+as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_prog_RC="$ac_prog"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+
+fi
+fi
+RC=$ac_cv_prog_RC
+if test -n "$RC"; then
+  echo "$as_me:$LINENO: result: $RC" >&5
+echo "${ECHO_T}$RC" >&6
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+  test -n "$RC" && break
+done
+test -n "$RC" || RC="none"
+
+	case $RC in
+	    windres)
+		rcdef_inc="--include "
+		rcdef_start="--define "
+		rcdef_q='\"'
+		RES_SUFFIX=res.o
+
+		PKG_OBJECTS="${PKG_OBJECTS} ${PACKAGE_NAME}.res.o" ;;
+	    rc)
+		rcdef_inc="/i "
+		rcdef_start="/d "
+		rcdef_q='"'
+		RES_SUFFIX=res
+
+		PKG_OBJECTS="${PKG_OBJECTS} ${PACKAGE_NAME}.res" ;;
+	    none)
+		{ echo "$as_me:$LINENO: WARNING: could not find resource compiler" >&5
+echo "$as_me: WARNING: could not find resource compiler" >&2;}
+		RC=: ;;
+	esac
+fi
+
+    for i in $dirs; do
+	RES_DEFS="${RES_DEFS} ${rcdef_inc}\"`${CYGPATH} $i`\""
+    done
+    for i in $vars; do
+	RES_DEFS="$RES_DEFS ${rcdef_start}$i='${rcdef_q}\$($i)${rcdef_q}'"
+    done
+
+
 
     echo "$as_me:$LINENO: checking for build with symbols" >&5
 echo $ECHO_N "checking for build with symbols... $ECHO_C" >&6
@@ -10233,6 +10233,8 @@ echo "${ECHO_T}enabled $tcl_ok debugging" >&6
 
 
 
+    CC_OUT="-o \$@"
+
     if test "$GCC" != yes \
 	    -a ${TEA_PLATFORM} == "windows" \
 	    -a "${SHARED_BUILD}" = "1"; then
@@ -10281,6 +10283,7 @@ test -n "$MT" || MT="none"
 
 	if test "$MT" != none; then
 
+	    CC_OUT="/Fo\$@"
 	    ADD_MANIFEST="${MT} -manifest \$@.manifest -outputresource:\$@\;2"
 
 	    CLEANFILES="$CLEANFILES ${PKG_LIB_FILE}.manifest"
@@ -11150,9 +11153,6 @@ s,@EGREP@,$EGREP,;t t
 s,@MATH_LIBS@,$MATH_LIBS,;t t
 s,@PKG_SOURCES@,$PKG_SOURCES,;t t
 s,@PKG_OBJECTS@,$PKG_OBJECTS,;t t
-s,@RC@,$RC,;t t
-s,@RES_SUFFIX@,$RES_SUFFIX,;t t
-s,@RES_DEFS@,$RES_DEFS,;t t
 s,@PKG_PRIVATE_HEADERS@,$PKG_PRIVATE_HEADERS,;t t
 s,@TCL_TOP_DIR_NATIVE@,$TCL_TOP_DIR_NATIVE,;t t
 s,@TCL_GENERIC_DIR_NATIVE@,$TCL_GENERIC_DIR_NATIVE,;t t
@@ -11176,6 +11176,9 @@ s,@SHLIB_LD@,$SHLIB_LD,;t t
 s,@SHLIB_LD_LIBS@,$SHLIB_LD_LIBS,;t t
 s,@SHLIB_CFLAGS@,$SHLIB_CFLAGS,;t t
 s,@LD_LIBRARY_PATH_VAR@,$LD_LIBRARY_PATH_VAR,;t t
+s,@RC@,$RC,;t t
+s,@RES_SUFFIX@,$RES_SUFFIX,;t t
+s,@RES_DEFS@,$RES_DEFS,;t t
 s,@CFLAGS_DEFAULT@,$CFLAGS_DEFAULT,;t t
 s,@LDFLAGS_DEFAULT@,$LDFLAGS_DEFAULT,;t t
 s,@TCL_DBGX@,$TCL_DBGX,;t t
@@ -11184,6 +11187,7 @@ s,@MAKE_SHARED_LIB@,$MAKE_SHARED_LIB,;t t
 s,@MAKE_STATIC_LIB@,$MAKE_STATIC_LIB,;t t
 s,@MAKE_STUB_LIB@,$MAKE_STUB_LIB,;t t
 s,@RANLIB_STUB@,$RANLIB_STUB,;t t
+s,@CC_OUT@,$CC_OUT,;t t
 s,@MT@,$MT,;t t
 s,@ADD_MANIFEST@,$ADD_MANIFEST,;t t
 s,@CLEANFILES@,$CLEANFILES,;t t
